accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordChangeView,
    PasswordChangeDoneView,
)

from accounts.views import (
    UserProfileView,
    CustomLoginView,
    RegisterView,
    CustomLogoutView,
)

app_name = "accounts"

urlpatterns = [
    path(
        "",
        CustomLoginView.as_view(),
        name="login_view",
    ),
    path(
        "profile/",
        UserProfileView.as_view(),
        name="user_profile_view",
    ),
    path(
        "register/",
        RegisterView.as_view(),
        name="register_view",
    ),
    path(
        "logout/",
        CustomLogoutView.as_view(),
        name="logout_view",
    ),
    path(
        "password/forgot/",
        PasswordResetView.as_view(
            email_template_name="accounts/password_forgot.html",
            template_name="accounts/password_forgot.html",
            success_url=reverse_lazy("accounts:password_forgot_done_view"),
            extra_context={"page_title": "Forgot Password"},
        ),
        name="password_forgot_view",
    ),
    path(
        "password/forgot/done/",
        PasswordResetDoneView.as_view(
            template_name="accounts/password_forgot_done.html",
            extra_context={"page_title": "Forgot Password"},
        ),
        name="password_forgot_done_view",
    ),
    path(
        "password/forgot/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="accounts/password_forgot_confirm.html",
            success_url=reverse_lazy("accounts:password_forgot_complete_view"),
            extra_context={"page_title": "Forgot Password"},
        ),
        name="password_forgot_confirm_view",
    ),
    path(
        "password/forgot/complete/",
        PasswordResetCompleteView.as_view(
            template_name="accounts/password_forgot_complete.html",
            extra_context={"page_title": "Forgot Password"},
        ),
        name="password_forgot_complete_view",
    ),
    path(
        "password/change/",
        login_required(
            PasswordChangeView.as_view(
                template_name="accounts/password_change.html",
                success_url=reverse_lazy("accounts:password_change_done_view"),
                extra_context={"page_title": "Change Password"},
            )
        ),
        name="password_change_view",
    ),
    path(
        "password/change/done/",
        login_required(
            PasswordResetDoneView.as_view(
                template_name="accounts/password_change_done.html",
                extra_context={"page_title": "Change Password"},
            )
        ),
        name="password_change_done_view",
    ),
]

core/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from core.views import (
    HomeView,
    NotificationAddView,
    NotificationDetailView,
    NotificationsListView,
)

app_name = "core"

urlpatterns = [
    path(
        "dashboard/",
        HomeView.as_view(),
        name="home_view",
    ),
    path(
        "notifications/",
        NotificationsListView.as_view(),
        name="notifications_list_view",
    ),
    path(
        "notification/<int:pk>/",
        NotificationDetailView.as_view(),
        name="notification_detail_view",
    ),
    path(
        "notification/add/", NotificationAddView.as_view(), name="notification_add_view"
    ),
    path(
        "instructions/",
        login_required(
            TemplateView.as_view(
                template_name="core/instructions.html",
                extra_context={"page_title": "Instructions"},
            )
        ),
        name="instructions_view",
    ),
]

notification/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render

from notification.routers import router


urlpatterns = [
    # admin urls
    path("admin/", admin.site.urls),
    # ...
    # /, /login, /register, /forgot-password
    path("", include("accounts.urls")),
    # ...
    # dashboard/,
    path("", include("analytics.urls")),
    # ...
    # notification/send, notifications
    path("", include("core.urls")),
    # ...
    # website/add/, website/delete/<id>/, website/<id>/
    path("", include("websites.urls")),
    # ...
    # all the api urls
    path("api/", include(router.urls)),
    # ...
    # service worker file
    re_path(
        r"^firebase-messaging-sw.js",
        TemplateView.as_view(
            template_name="firebase-messaging-sw.js",
            content_type="application/javascript",
        ),
    ),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(
        [
            path("__debug__/", include(debug_toolbar.urls)),
        ]
    )


def error_page(request, *args, **kwargs):
    return render(request, "404.html")


handler404 = error_page
handler500 = error_page
handler403 = error_page
handler400 = error_page

pushify/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render

from pushify.routers import router


urlpatterns = [
    # admin urls
    path("admin/", admin.site.urls),
    # ...
    # /, /login, /register, /forgot-password
    path("", include("accounts.urls")),
    # ...
    # dashboard/,
    path("", include("analytics.urls")),
    # ...
    # notification/send, notifications
    path("", include("core.urls")),
    # ...
    # website/add/, website/delete/<id>/, website/<id>/
    path("", include("websites.urls")),
    # ...
    # all the api urls
    path("api/", include(router.urls)),
    # ...
    # service worker file
    re_path(
        r"^firebase-messaging-sw.js",
        TemplateView.as_view(
            template_name="firebase-messaging-sw.js",
            content_type="application/javascript",
        ),
    ),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(
        [
            path("__debug__/", include(debug_toolbar.urls)),
        ]
    )


def error_page(request, *args, **kwargs):
    return render(request, "404.html")


handler404 = error_page
handler500 = error_page
handler403 = error_page
handler400 = error_page

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinLengthValidator
from django.conf import settings

from accounts.managers import CustomUserManager

# Create your models here.


class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(
        max_length=50,
        verbose_name=_("Username"),
        help_text="Username should be unique.",
        unique=True,
        validators=(MinLengthValidator(settings.MIN_USERNAME_LENGTH),),
        null=True,
        blank=True,
    )
    full_name = models.CharField(max_length=255, verbose_name=_("Full Name"))
    picture = models.ImageField(upload_to="profile_pictures", null=True, blank=True)

    first_name = None
    last_name = None

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = [
        "full_name",
    ]

    objects = CustomUserManager()

    def __str__(self):
        return self.email

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("full_name", "email", "password1", "password2")


class CustomUserChangeForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = (
            "full_name",
            "picture",
            "email",
            "username",
        )


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            "full_name",
            "picture",
            "email",
            "username",
        )

accounts/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, UpdateView
from django.contrib import messages
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import (
    authenticate,
    login,
    logout,
    get_user_model,
)

from django.contrib.auth.views import LoginView, LogoutView

from accounts.forms import CustomUserCreationForm, UserProfileForm

# Create your views here.

User = get_user_model()


class UserProfileView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    template_name = "accounts/user_profile.html"
    extra_context = {"page_title": "Profile"}
    form_class = UserProfileForm
    success_message = "Successfully saved the profile details."
    success_url = reverse_lazy("accounts:user_profile_view")

    def get_object(self):
        return self.request.user


class CustomLoginView(SuccessMessageMixin, LoginView):
    template_name = "accounts/login.html"
    extra_context = {"page_title": "Login"}
    success_message = "Welcome to the Website."

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(request.META.get("HTTP_REFERER") or "core:home_view")
        return super().get(request, *args, **kwargs)


class RegisterView(SuccessMessageMixin, View):
    template_name = "accounts/register.html"
    form_class = CustomUserCreationForm
    extra_context = {"page_title": "User Registration"}
    success_message = "Successfully registered, You can go ahead and login now."
    success_url = reverse_lazy("accounts:login_view")

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(request.META.get("HTTP_REFERER") or "core:home_view")
        context = {"form": self.form_class()}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect(self.success_url)

        context = {"form": form}
        return render(request, self.template_name, context)


class CustomLogoutView(SuccessMessageMixin, LogoutView):
    success_message = "We hope to see you back soon."

    def post(self, request, *args, **kwargs):
        # is user is not authenticated
        logout(request)
        return redirect(self.next_page)

templates/accounts/change_password.html
{% extends 'core/base.html' %} 


{% block page_content %}

<div class="container">
  <!-- Outer Row -->
  <div class="row justify-content-center">
    <div class="col-xl-10 col-lg-12 col-md-9">
      <div class="o-hidden border-0 my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-lg-12">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-4">Want to change your password ?</h1>
                  {% comment %} <p class="mb-4">
                    We get it, stuff happens. Just enter your email address below and we'll send you a link to reset
                    your password!
                  </p> {% endcomment %}
                </div>
                <form class="user" method="POST">
                  <div class="form-group">
                    <input
                      type="password"
                      class="form-control form-control-user"
                      id="old_password"
                      aria-describedby="old password"
                      placeholder="Old Password"
                    />
                </div>
                <div class="form-group">
                    <input
                      type="password"
                      class="form-control form-control-user"
                      id="new_password1"
                      aria-describedby="new password"
                      placeholder="New Password"
                    />
                  </div>
                  <div class="form-group">
                    <input
                      type="password"
                      class="form-control form-control-user"
                      id="new_password2"
                      aria-describedby="retype new password"
                      placeholder="Retype New Password"
                    />
                  </div>
                  <button type="submit" class="btn btn-primary btn-user btn-block">Change Password</button>
                </form>
                <hr />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/accounts/forgot-password.html
{% extends 'base.html' %} 

{% block body_content %}

<div class="container">
  <!-- Outer Row -->
  <div class="row justify-content-center">
    <div class="col-xl-10 col-lg-12 col-md-9">
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
            <div class="col-lg-6">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                  <p class="mb-4">
                    We get it, stuff happens. Just enter your email address below and we'll send you a link to reset
                    your password!
                  </p>
                </div>
                <form class="user">
                  <div class="form-group">
                    <input
                      type="email"
                      class="form-control form-control-user"
                      id="exampleInputEmail"
                      aria-describedby="emailHelp"
                      placeholder="Enter Email Address..."
                    />
                  </div>
                  <a href="login.html" class="btn btn-primary btn-user btn-block"> Reset Password </a>
                </form>
                <hr />
                <div class="text-center">
                  <a class="small" href="register.html">Create an Account!</a>
                </div>
                <div class="text-center">
                  <a class="small" href="login.html">Already have an account? Login!</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/accounts/forgot_password.html
{% extends 'base.html' %} 


{% block body_content %}

<div class="container">
  <!-- Outer Row -->
  <div class="row justify-content-center">
    <div class="col-xl-10 col-lg-12 col-md-9">
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
            <div class="col-lg-6">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                  <p class="mb-4">
                    We get it, stuff happens. Just enter your email address below and we'll send you a link to reset
                    your password!
                  </p>
                </div>
                <form class="user" method="POST">
                  <div class="form-group">
                    <input
                      type="email"
                      class="form-control form-control-user"
                      id="exampleInputEmail"
                      aria-describedby="emailHelp"
                      placeholder="Enter Email Address..."
                    />
                  </div>
                  <button type="submit" class="btn btn-primary btn-user btn-block">Reset Password</button>
                </form>
                <hr />
                <div class="text-center">
                  <a class="small" href="{% url 'accounts:register_view' %}">Create an Account!</a>
                </div>
                <div class="text-center">
                  <a class="small" href="{% url 'accounts:login_view' %}">Already have an account? Login!</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %} 

{% block body_content %}

<div class="container">
  <!-- Outer Row -->
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-12">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-4">Welcome</h1>
                </div>
                <form class="user" method='POST'>
                  {% csrf_token %} {{ form|crispy }}
                  {% comment %} <div class="form-group">
                    <input
                      type="email"
                      class="form-control form-control-user"
                      id="exampleInputEmail"
                      aria-describedby="emailHelp"
                      placeholder="Enter Email Address..."
                    />
                  </div>
                  <div class="form-group">
                    <input
                      type="password"
                      class="form-control form-control-user"
                      id="exampleInputPassword"
                      placeholder="Password"
                    />
                  </div>
                  <div class="form-group">
                    <div class="custom-control custom-checkbox small">
                      <input type="checkbox" class="custom-control-input" id="customCheck" />
                      <label class="custom-control-label" for="customCheck">Remember Me</label>
                    </div>
                  </div> {% endcomment %}
                  <button type="submit" class="btn btn-primary shadow-sm btn-block">Login</button>
                  {% comment %}
                  <hr />
                  <a href="index.html" class="btn btn-google btn-user btn-block">
                    <i class="fab fa-google fa-fw"></i> Login with Google
                  </a>
                  <a href="index.html" class="btn btn-facebook btn-user btn-block">
                    <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook
                  </a>
                  {% endcomment %}
                </form>
                <hr />
                <div class="text-center">
                  <a class="small" href="{% url 'accounts:password_forgot_view' %}">Forgot Password?</a>
                </div>
                <div class="text-center">
                  <a class="small" href="{% url 'accounts:register_view' %}">Create an Account!</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/accounts/password_change_done.html
{% extends 'core/base.html' %} {% block page_content %}

<div class="container">
  <!-- Outer Row -->
  <div class="row justify-content-center">
    <div class="col-12">
      <div class="o-hidden border-0 my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="text-center">
            <h1 class="h3 text-gray-800 mb-4">Confirmation!</h1>
          </div>
          <hr />
          <p class="text-center lead">Successfully changed the password, go back to <a href="{% url 'core:home_view' %}">home</a>.</p>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/accounts/password_forgot.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %} 

{% block body_content %}

<div class="container">
  <!-- Outer Row -->
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-12">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                  <p class="mb-4">
                    We get it, stuff happens. Just enter your email address below and we'll send you a link to reset
                    your password!
                  </p>
                </div>
                <form class="user" method="POST">
                  {% csrf_token %} {{ form|crispy }}
                  {% comment %} <div class="form-group">
                    <input
                      type="email"
                      class="form-control form-control-user"
                      id="exampleInputEmail"
                      aria-describedby="emailHelp"
                      placeholder="Enter Email Address..."
                    />
                  </div> {% endcomment %}
                  <button type="submit" class="btn btn-primary shadow-sm btn-block">Reset Password</button>
                </form>
                <hr />
                <div class="text-center">
                  <a class="small" href="{% url 'accounts:register_view' %}">Create an Account!</a>
                </div>
                <div class="text-center">
                  <a class="small" href="{% url 'accounts:login_view' %}">Already have an account? Login!</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/accounts/password_forgot_complete.html
{% extends 'base.html' %} 


{% block body_content %}

<div class="container">
  <!-- Outer Row -->
  <div class="row justify-content-center">
    <div class="col-xl-10 col-lg-12 col-md-9">
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
            <div class="col-lg-6">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                  <p class="mb-4">
                    We get it, stuff happens. Just enter your email address below and we'll send you a link to reset
                    your password!
                  </p>
                </div>
                <h1>Password Reset Complete</h1>
                <hr />
                <div class="text-center">
                  <a class="small" href="{% url 'accounts:register_view' %}">Create an Account!</a>
                </div>
                <div class="text-center">
                  <a class="small" href="{% url 'accounts:login_view' %}">Already have an account? Login!</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/accounts/password_forgot_confirm.html
{% extends 'base.html' %} 


{% block body_content %}

<div class="container">
  <!-- Outer Row -->
  <div class="row justify-content-center">
    <div class="col-xl-10 col-lg-12 col-md-9">
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
            <div class="col-lg-6">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                  <p class="mb-4">
                    We get it, stuff happens. Just enter your email address below and we'll send you a link to reset
                    your password!
                  </p>
                </div>
                <h1>Password Reset Confirm</h1>
                <hr />
                <div class="text-center">
                  <a class="small" href="{% url 'accounts:register_view' %}">Create an Account!</a>
                </div>
                <div class="text-center">
                  <a class="small" href="{% url 'accounts:login_view' %}">Already have an account? Login!</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/accounts/password_forgot_done.html
{% extends 'base.html' %} 


{% block body_content %}

<div class="container">
  <!-- Outer Row -->
  <div class="row justify-content-center">
    <div class="col-xl-10 col-lg-12 col-md-9">
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
            <div class="col-lg-6">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                  <p class="mb-4">
                    We get it, stuff happens. Just enter your email address below and we'll send you a link to reset
                    your password!
                  </p>
                </div>
                <h1>Password Reset Done</h1>
                <hr />
                <div class="text-center">
                  <a class="small" href="{% url 'accounts:register_view' %}">Create an Account!</a>
                </div>
                <div class="text-center">
                  <a class="small" href="{% url 'accounts:login_view' %}">Already have an account? Login!</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %} 

{% block body_content %}

<div class="container">
  <!-- Outer Row -->
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-12">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                </div>
                <form class="user" method='POST'>
                  {% csrf_token %} {{ form|crispy }}
                  {% comment %} <div class="form-group">
                    <input
                      type="text"
                      class="form-control form-control-user"
                      id="exampleFullName"
                      placeholder="Full Name"
                    />
                  </div>
                  <div class="form-group">
                    <input
                      type="email"
                      class="form-control form-control-user"
                      id="exampleInputEmail"
                      placeholder="Email Address"
                    />
                  </div>
                  <div class="form-group row">
                    <div class="col-sm-6 mb-3 mb-sm-0">
                      <input
                        type="password"
                        class="form-control form-control-user"
                        id="exampleInputPassword"
                        placeholder="Password"
                      />
                    </div>
                    <div class="col-sm-6">
                      <input
                        type="password"
                        class="form-control form-control-user"
                        id="exampleRepeatPassword"
                        placeholder="Repeat Password"
                      />
                    </div>
                  </div> {% endcomment %}
                  <button type="submit" class="btn btn-primary shadow-sm btn-block">Register Account</button>
                  {% comment %}
                  <hr />
                  <a href="index.html" class="btn btn-google btn-user btn-block">
                    <i class="fab fa-google fa-fw"></i> Register with Google
                  </a>
                  <a href="index.html" class="btn btn-facebook btn-user btn-block">
                    <i class="fab fa-facebook-f fa-fw"></i> Register with Facebook
                  </a>
                  {% endcomment %}
                </form>
                <hr />
                <div class="text-center">
                  <a class="small" href="{% url 'accounts:password_forgot_view' %}">Forgot Password?</a>
                </div>
                <div class="text-center">
                  <a class="small" href="{% url 'accounts:login_view' %}">Already have an account? Login!</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}