accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordChangeView,
    PasswordChangeDoneView,
)

from accounts.views import (
    UserProfileView,
    CustomLoginView,
    RegisterView,
    CustomLogoutView,
)

app_name = "accounts"

urlpatterns = [
    path(
        "",
        CustomLoginView.as_view(),
        name="login_view",
    ),
    path(
        "profile/",
        UserProfileView.as_view(),
        name="user_profile_view",
    ),
    path(
        "register/",
        RegisterView.as_view(),
        name="register_view",
    ),
    path(
        "logout/",
        CustomLogoutView.as_view(),
        name="logout_view",
    ),
    path(
        "password/forgot/",
        PasswordResetView.as_view(
            email_template_name="accounts/password_forgot.html",
            template_name="accounts/password_forgot.html",
            success_url=reverse_lazy("accounts:password_forgot_done_view"),
            extra_context={"page_title": "Forgot Password"},
        ),
        name="password_forgot_view",
    ),
    path(
        "password/forgot/done/",
        PasswordResetDoneView.as_view(
            template_name="accounts/password_forgot_done.html",
            extra_context={"page_title": "Forgot Password"},
        ),
        name="password_forgot_done_view",
    ),
    path(
        "password/forgot/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="accounts/password_forgot_confirm.html",
            success_url=reverse_lazy("accounts:password_forgot_complete_view"),
            extra_context={"page_title": "Forgot Password"},
        ),
        name="password_forgot_confirm_view",
    ),
    path(
        "password/forgot/complete/",
        PasswordResetCompleteView.as_view(
            template_name="accounts/password_forgot_complete.html",
            extra_context={"page_title": "Forgot Password"},
        ),
        name="password_forgot_complete_view",
    ),
    path(
        "password/change/",
        login_required(
            PasswordChangeView.as_view(
                template_name="accounts/password_change.html",
                success_url=reverse_lazy("accounts:password_change_done_view"),
                extra_context={"page_title": "Change Password"},
            )
        ),
        name="password_change_view",
    ),
    path(
        "password/change/done/",
        login_required(
            PasswordResetDoneView.as_view(
                template_name="accounts/password_change_done.html",
                extra_context={"page_title": "Change Password"},
            )
        ),
        name="password_change_done_view",
    ),
]

core/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from core.views import (
    HomeView,
    NotificationAddView,
    NotificationDetailView,
    NotificationsListView,
)

app_name = "core"

urlpatterns = [
    path(
        "dashboard/",
        HomeView.as_view(),
        name="home_view",
    ),
    path(
        "notifications/",
        NotificationsListView.as_view(),
        name="notifications_list_view",
    ),
    path(
        "notification/<int:pk>/",
        NotificationDetailView.as_view(),
        name="notification_detail_view",
    ),
    path(
        "notification/add/", NotificationAddView.as_view(), name="notification_add_view"
    ),
    path(
        "instructions/",
        login_required(
            TemplateView.as_view(
                template_name="core/instructions.html",
                extra_context={"page_title": "Instructions"},
            )
        ),
        name="instructions_view",
    ),
]

notification/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render

from notification.routers import router


urlpatterns = [
    # admin urls
    path("admin/", admin.site.urls),
    # ...
    # /, /login, /register, /forgot-password
    path("", include("accounts.urls")),
    # ...
    # dashboard/,
    path("", include("analytics.urls")),
    # ...
    # notification/send, notifications
    path("", include("core.urls")),
    # ...
    # website/add/, website/delete/<id>/, website/<id>/
    path("", include("websites.urls")),
    # ...
    # all the api urls
    path("api/", include(router.urls)),
    # ...
    # service worker file
    re_path(
        r"^firebase-messaging-sw.js",
        TemplateView.as_view(
            template_name="firebase-messaging-sw.js",
            content_type="application/javascript",
        ),
    ),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(
        [
            path("__debug__/", include(debug_toolbar.urls)),
        ]
    )


def error_page(request, *args, **kwargs):
    return render(request, "404.html")


handler404 = error_page
handler500 = error_page
handler403 = error_page
handler400 = error_page

pushify/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render

from pushify.routers import router


urlpatterns = [
    # admin urls
    path("admin/", admin.site.urls),
    # ...
    # /, /login, /register, /forgot-password
    path("", include("accounts.urls")),
    # ...
    # dashboard/,
    path("", include("analytics.urls")),
    # ...
    # notification/send, notifications
    path("", include("core.urls")),
    # ...
    # website/add/, website/delete/<id>/, website/<id>/
    path("", include("websites.urls")),
    # ...
    # all the api urls
    path("api/", include(router.urls)),
    # ...
    # service worker file
    re_path(
        r"^firebase-messaging-sw.js",
        TemplateView.as_view(
            template_name="firebase-messaging-sw.js",
            content_type="application/javascript",
        ),
    ),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(
        [
            path("__debug__/", include(debug_toolbar.urls)),
        ]
    )


def error_page(request, *args, **kwargs):
    return render(request, "404.html")


handler404 = error_page
handler500 = error_page
handler403 = error_page
handler400 = error_page

templates/includes/topbar/alert.html
<!-- Nav Item - Alerts -->
<li class="nav-item dropdown no-arrow mx-1">
  <a
    class="nav-link dropdown-toggle"
    href="#"
    id="alertsDropdown"
    role="button"
    data-toggle="dropdown"
    aria-haspopup="true"
    aria-expanded="false"
  >
    <i class="fas fa-bell fa-fw"></i>
    <!-- Counter - Alerts -->
    <span class="badge badge-danger badge-counter">3+</span>
  </a>
  <!-- Dropdown - Alerts -->
  <div
    class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
    aria-labelledby="alertsDropdown"
  >
    <h6 class="dropdown-header">Alerts Center</h6>
    <a class="dropdown-item d-flex align-items-center" href="#">
      <div class="mr-3">
        <div class="icon-circle bg-primary">
          <i class="fas fa-file-alt text-white"></i>
        </div>
      </div>
      <div>
        <div class="small text-gray-500">December 12, 2019</div>
        <span class="font-weight-bold">A new monthly report is ready to download!</span>
      </div>
    </a>
    <a class="dropdown-item d-flex align-items-center" href="#">
      <div class="mr-3">
        <div class="icon-circle bg-success">
          <i class="fas fa-donate text-white"></i>
        </div>
      </div>
      <div>
        <div class="small text-gray-500">December 7, 2019</div>
        $290.29 has been deposited into your account!
      </div>
    </a>
    <a class="dropdown-item d-flex align-items-center" href="#">
      <div class="mr-3">
        <div class="icon-circle bg-warning">
          <i class="fas fa-exclamation-triangle text-white"></i>
        </div>
      </div>
      <div>
        <div class="small text-gray-500">December 2, 2019</div>
        Spending Alert: We've noticed unusually high spending for your account.
      </div>
    </a>
    <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
  </div>
</li>

templates/includes/topbar/index.html
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
  <!-- Sidebar Toggle (Topbar) -->
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>

  {% comment %} {% include 'includes/topbar/search.html' %} {% endcomment %}

  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">

    {% comment %} 

    {% include 'includes/topbar/search_dropdown.html' %} 

    {% include 'includes/topbar/alert.html' %} 
    
    {% include 'includes/topbar/messages.html' %} 
    
    {% endcomment %}

    <div class="topbar-divider d-none d-sm-block"></div>

    {% if request.user.is_authenticated %}
      {% include 'includes/topbar/user.html' %}
    {% else %}
      {% include 'includes/topbar/register_buttons.html' %}
    {% endif %}

  </ul>
</nav>
<!-- End of Topbar -->

templates/includes/topbar/messages.html
<!-- Nav Item - Messages -->
<li class="nav-item dropdown no-arrow mx-1">
  <a
    class="nav-link dropdown-toggle"
    href="#"
    id="messagesDropdown"
    role="button"
    data-toggle="dropdown"
    aria-haspopup="true"
    aria-expanded="false"
  >
    <i class="fas fa-envelope fa-fw"></i>
    <!-- Counter - Messages -->
    <span class="badge badge-danger badge-counter">7</span>
  </a>
  <!-- Dropdown - Messages -->
  <div
    class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
    aria-labelledby="messagesDropdown"
  >
    <h6 class="dropdown-header">Message Center</h6>
    <a class="dropdown-item d-flex align-items-center" href="#">
      <div class="dropdown-list-image mr-3">
        <img class="rounded-circle" src="img/undraw_profile_1.svg" alt="" />
        <div class="status-indicator bg-success"></div>
      </div>
      <div class="font-weight-bold">
        <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
        <div class="small text-gray-500">Emily Fowler · 58m</div>
      </div>
    </a>
    <a class="dropdown-item d-flex align-items-center" href="#">
      <div class="dropdown-list-image mr-3">
        <img class="rounded-circle" src="img/undraw_profile_2.svg" alt="" />
        <div class="status-indicator"></div>
      </div>
      <div>
        <div class="text-truncate">
          I have the photos that you ordered last month, how would you like them sent to you?
        </div>
        <div class="small text-gray-500">Jae Chun · 1d</div>
      </div>
    </a>
    <a class="dropdown-item d-flex align-items-center" href="#">
      <div class="dropdown-list-image mr-3">
        <img class="rounded-circle" src="img/undraw_profile_3.svg" alt="" />
        <div class="status-indicator bg-warning"></div>
      </div>
      <div>
        <div class="text-truncate">
          Last month's report looks great, I am very happy with the progress so far, keep up the good work!
        </div>
        <div class="small text-gray-500">Morgan Alvarez · 2d</div>
      </div>
    </a>
    <a class="dropdown-item d-flex align-items-center" href="#">
      <div class="dropdown-list-image mr-3">
        <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="" />
        <div class="status-indicator bg-success"></div>
      </div>
      <div>
        <div class="text-truncate">
          Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they
          aren't good...
        </div>
        <div class="small text-gray-500">Chicken the Dog · 2w</div>
      </div>
    </a>
    <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
  </div>
</li>

templates/includes/topbar/register_buttons.html
<!-- Register Buttons -->
<li class="nav-item dropdown no-arrow">
  <a class="btn btn-sm btn-primary shadow-sm" href="{% url 'accounts:login_view' %}">Login</a>
  <a class="btn btn-sm btn-info shadow-sm" href="{% url 'accounts:register_view' %}">Register</a>
</li>

templates/includes/topbar/search.html
<!-- Topbar Search -->
<form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
  <div class="input-group">
    <input
      type="text"
      class="form-control bg-light border-0 small"
      placeholder="Search for..."
      aria-label="Search"
      aria-describedby="basic-addon2"
    />
    <div class="input-group-append">
      <button class="btn btn-primary" type="button">
        <i class="fas fa-search fa-sm"></i>
      </button>
    </div>
  </div>
</form>

templates/includes/topbar/search_dropdown.html
<!-- Nav Item - Search Dropdown (Visible Only XS) -->
<li class="nav-item dropdown no-arrow d-sm-none">
  <a
    class="nav-link dropdown-toggle"
    href="#"
    id="searchDropdown"
    role="button"
    data-toggle="dropdown"
    aria-haspopup="true"
    aria-expanded="false"
  >
    <i class="fas fa-search fa-fw"></i>
  </a>
  <!-- Dropdown - Messages -->
  <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
    <form class="form-inline mr-auto w-100 navbar-search">
      <div class="input-group">
        <input
          type="text"
          class="form-control bg-light border-0 small"
          placeholder="Search for..."
          aria-label="Search"
          aria-describedby="basic-addon2"
        />
        <div class="input-group-append">
          <button class="btn btn-primary" type="button">
            <i class="fas fa-search fa-sm"></i>
          </button>
        </div>
      </div>
    </form>
  </div>
</li>

templates/includes/topbar/user.html
{% load static %}

<!-- Nav Item - User Information -->
<li class="nav-item dropdown no-arrow">
  <a
    class="nav-link dropdown-toggle"
    href="#"
    id="userDropdown"
    role="button"
    data-toggle="dropdown"
    aria-haspopup="true"
    aria-expanded="false"
  >
    <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ request.user.full_name }}</span>
    <img
      class="img-profile rounded-circle"
      src="{%  if request.user.picture %}{{ request.user.picture.url }}{% else %}{% static 'img/undraw_profile.svg' %}{% endif %}"
    />
  </a>
  <!-- Dropdown - User Information -->
  <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
    <a class="dropdown-item" href="{% url 'accounts:user_profile_view' %}">
      <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
      Profile
    </a>
    <a class="dropdown-item" href="{% url 'accounts:password_change_view' %}">
      <i class="fas fa-key fa-sm fa-fw mr-2 text-gray-400"></i>
      Change Password
    </a>
    {% if request.user.is_superuser %}
    <a class="dropdown-item" href="{% url 'admin:index' %}">
      <i class="fas fa-user-cog fa-sm fa-fw mr-2 text-gray-400"></i>
      Admin
    </a>
    {% endif %}
    <div class="dropdown-divider"></div>
      <a class="dropdown-item text-center text-muted" data-toggle="modal" data-target="#logoutModal" href='javascript:void(0)'>
        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>Logout
      </a>
  </div>
</li>