core/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from core.views import (
    HomeView,
    NotificationAddView,
    NotificationDetailView,
    NotificationsListView,
)

app_name = "core"

urlpatterns = [
    path(
        "dashboard/",
        HomeView.as_view(),
        name="home_view",
    ),
    path(
        "notifications/",
        NotificationsListView.as_view(),
        name="notifications_list_view",
    ),
    path(
        "notification/<int:pk>/",
        NotificationDetailView.as_view(),
        name="notification_detail_view",
    ),
    path(
        "notification/add/", NotificationAddView.as_view(), name="notification_add_view"
    ),
    path(
        "instructions/",
        login_required(
            TemplateView.as_view(
                template_name="core/instructions.html",
                extra_context={"page_title": "Instructions"},
            )
        ),
        name="instructions_view",
    ),
]

notification/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render

from notification.routers import router


urlpatterns = [
    # admin urls
    path("admin/", admin.site.urls),
    # ...
    # /, /login, /register, /forgot-password
    path("", include("accounts.urls")),
    # ...
    # dashboard/,
    path("", include("analytics.urls")),
    # ...
    # notification/send, notifications
    path("", include("core.urls")),
    # ...
    # website/add/, website/delete/<id>/, website/<id>/
    path("", include("websites.urls")),
    # ...
    # all the api urls
    path("api/", include(router.urls)),
    # ...
    # service worker file
    re_path(
        r"^firebase-messaging-sw.js",
        TemplateView.as_view(
            template_name="firebase-messaging-sw.js",
            content_type="application/javascript",
        ),
    ),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(
        [
            path("__debug__/", include(debug_toolbar.urls)),
        ]
    )


def error_page(request, *args, **kwargs):
    return render(request, "404.html")


handler404 = error_page
handler500 = error_page
handler403 = error_page
handler400 = error_page

pushify/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render

from pushify.routers import router


urlpatterns = [
    # admin urls
    path("admin/", admin.site.urls),
    # ...
    # /, /login, /register, /forgot-password
    path("", include("accounts.urls")),
    # ...
    # dashboard/,
    path("", include("analytics.urls")),
    # ...
    # notification/send, notifications
    path("", include("core.urls")),
    # ...
    # website/add/, website/delete/<id>/, website/<id>/
    path("", include("websites.urls")),
    # ...
    # all the api urls
    path("api/", include(router.urls)),
    # ...
    # service worker file
    re_path(
        r"^firebase-messaging-sw.js",
        TemplateView.as_view(
            template_name="firebase-messaging-sw.js",
            content_type="application/javascript",
        ),
    ),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(
        [
            path("__debug__/", include(debug_toolbar.urls)),
        ]
    )


def error_page(request, *args, **kwargs):
    return render(request, "404.html")


handler404 = error_page
handler500 = error_page
handler403 = error_page
handler400 = error_page

websites/urls.py
from django.urls import path

from websites.views import (
    WebsiteAddView,
    WebsiteEditView,
    WebsitesListView,
    WebsiteDeleteView,
)

app_name = "websites"

urlpatterns = [
    path("websites/", WebsitesListView.as_view(), name="websites_list_view"),
    path("website/add/", WebsiteAddView.as_view(), name="website_add_view"),
    path("website/<slug:slug>/", WebsiteEditView.as_view(), name="website_edit_view"),
    path(
        "website/delete/<int:pk>/",
        WebsiteDeleteView.as_view(),
        name="website_delete_view",
    ),
]

templates/includes/footer.html
<!-- Footer -->
<footer class="sticky-footer bg-white mt-5">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Copyright &copy; Pushify 2021</span>
    </div>
  </div>
</footer>
<!-- End of Footer -->

templates/includes/sidebar.html
{% url 'core:home_view' as home_view %} 
{% url 'websites:website_add_view' as website_add_view %} 
{% url 'websites:websites_list_view' as websites_list_view %} 
{% url 'core:notification_add_view' as notification_add_view %} 
{% url 'core:notifications_list_view' as notifications_list_view %} 
{% url 'core:instructions_view' as instructions_view %} 



<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'core:home_view' %}">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-laugh-wink"></i>
    </div>
    <div class="sidebar-brand-text mx-3">Pushify</div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0" />

  <!-- Nav Item - Home -->
  <li class="nav-item {% if request.path == home_view %}active{% endif %}">
    <a class="nav-link" href="{% url 'core:home_view' %}">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Home</span></a
    >
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider" />

  <!-- Heading -->
  <div class="sidebar-heading">Managment</div>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a
      class="nav-link collapsed"
      href="#"
      data-toggle="collapse"
      data-target="#websiteManagementCollapse"
      aria-expanded="true"
      aria-controls="websiteManagementCollapse"
    >
      <i class="fab fa-fw fa-safari"></i>
      <span>Websites</span>
    </a>
    <div id="websiteManagementCollapse" class="collapse {% if request.path == website_add_view or request.path == websites_list_view %}show{% endif %}" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Manage:</h6>
        {% comment %} {% if request.user.is_superuser %} {% endcomment %}
        <a class="collapse-item {% if request.path == website_add_view %}active{% endif %}" href="{% url 'websites:website_add_view' %}">Add Website</a>
        {% comment %} {% endif %} {% endcomment %}
        <a class="collapse-item {% if request.path == websites_list_view %}active{% endif %}" href="{% url 'websites:websites_list_view' %}">Show All Website</a>
      </div>
    </div>
  </li>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a
      class="nav-link collapsed"
      href="#"
      data-toggle="collapse"
      data-target="#notificationManagementCollapse"
      aria-expanded="true"
      aria-controls="notificationManagementCollapse"
    >
      <i class="fas fa-fw fa-bell"></i>
      <span>Notification History</span>
    </a>
    <div
      id="notificationManagementCollapse"
      class="collapse {% if request.path == notification_add_view or request.path == notifications_list_view %}show{% endif %}"
      aria-labelledby="headingTwo"
      data-parent="#accordionSidebar"
    >
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Manage:</h6>
        <a class="collapse-item {% if request.path == notification_add_view %}active{% endif %}" href="{% url 'core:notification_add_view' %}">Create Notification</a>
        <a class="collapse-item {% if request.path == notifications_list_view %}active{% endif %}" href="{% url 'core:notifications_list_view' %}">Show All Notification</a>
      </div>
    </div>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider" />

  <!-- Heading -->
  <div class="sidebar-heading">Help</div>

  <!-- Nav Item - Tables -->
  <li class="nav-item {% if request.path == instructions_view %}active{% endif %}">
    <a class="nav-link" href="{% url 'core:instructions_view' %}">
      <i class="fas fa-fw fa-table"></i>
      <span>Instructions</span></a
    >
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block" />

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>

  <!-- Sidebar Message -->
  <div class="sidebar-card">
    <p class="text-center mb-2">Welcome</p>
  </div>
</ul>
<!-- End of Sidebar -->

templates/includes/toast.html
<!-- Toast Notifications -->
<div class="position-absolute p-3" style="z-index: 1000; right: 0; top: 5em;">
  <div
    id="liveToast"
    class="toast"
    role="alert"
    aria-live="assertive"
    aria-atomic="true"
    data-delay="30000"
  >
    <div class="toast-body">
      <strong class="mr-auto text-info">{{ message }}</strong>
      <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
</div>

templates/includes/topbar.html
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
  <!-- Sidebar Toggle (Topbar) -->
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>

  {% comment %} {% include 'includes/topbar/search.html' %} {% endcomment %}

  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">

    {% comment %} 

    {% include 'includes/topbar/search_dropdown.html' %} 

    {% include 'includes/topbar/alert.html' %} 
    
    {% include 'includes/topbar/messages.html' %} 
    
    {% endcomment %}

    <div class="topbar-divider d-none d-sm-block"></div>

    {% if request.user.is_authenticated %}
      {% include 'includes/topbar/user.html' %}
    {% else %}
      {% include 'includes/topbar/register_buttons.html' %}
    {% endif %}

  </ul>
</nav>
<!-- End of Topbar -->