accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordChangeView,
    PasswordChangeDoneView,
)

from accounts.views import (
    UserProfileView,
    CustomLoginView,
    RegisterView,
    CustomLogoutView,
)

app_name = "accounts"

urlpatterns = [
    path(
        "",
        CustomLoginView.as_view(),
        name="login_view",
    ),
    path(
        "profile/",
        UserProfileView.as_view(),
        name="user_profile_view",
    ),
    path(
        "register/",
        RegisterView.as_view(),
        name="register_view",
    ),
    path(
        "logout/",
        CustomLogoutView.as_view(),
        name="logout_view",
    ),
    path(
        "password/forgot/",
        PasswordResetView.as_view(
            email_template_name="accounts/password_forgot.html",
            template_name="accounts/password_forgot.html",
            success_url=reverse_lazy("accounts:password_forgot_done_view"),
            extra_context={"page_title": "Forgot Password"},
        ),
        name="password_forgot_view",
    ),
    path(
        "password/forgot/done/",
        PasswordResetDoneView.as_view(
            template_name="accounts/password_forgot_done.html",
            extra_context={"page_title": "Forgot Password"},
        ),
        name="password_forgot_done_view",
    ),
    path(
        "password/forgot/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="accounts/password_forgot_confirm.html",
            success_url=reverse_lazy("accounts:password_forgot_complete_view"),
            extra_context={"page_title": "Forgot Password"},
        ),
        name="password_forgot_confirm_view",
    ),
    path(
        "password/forgot/complete/",
        PasswordResetCompleteView.as_view(
            template_name="accounts/password_forgot_complete.html",
            extra_context={"page_title": "Forgot Password"},
        ),
        name="password_forgot_complete_view",
    ),
    path(
        "password/change/",
        login_required(
            PasswordChangeView.as_view(
                template_name="accounts/password_change.html",
                success_url=reverse_lazy("accounts:password_change_done_view"),
                extra_context={"page_title": "Change Password"},
            )
        ),
        name="password_change_view",
    ),
    path(
        "password/change/done/",
        login_required(
            PasswordResetDoneView.as_view(
                template_name="accounts/password_change_done.html",
                extra_context={"page_title": "Change Password"},
            )
        ),
        name="password_change_done_view",
    ),
]

core/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from core.views import (
    HomeView,
    NotificationAddView,
    NotificationDetailView,
    NotificationsListView,
)

app_name = "core"

urlpatterns = [
    path(
        "dashboard/",
        HomeView.as_view(),
        name="home_view",
    ),
    path(
        "notifications/",
        NotificationsListView.as_view(),
        name="notifications_list_view",
    ),
    path(
        "notification/<int:pk>/",
        NotificationDetailView.as_view(),
        name="notification_detail_view",
    ),
    path(
        "notification/add/", NotificationAddView.as_view(), name="notification_add_view"
    ),
    path(
        "instructions/",
        login_required(
            TemplateView.as_view(
                template_name="core/instructions.html",
                extra_context={"page_title": "Instructions"},
            )
        ),
        name="instructions_view",
    ),
]

notification/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render

from notification.routers import router


urlpatterns = [
    # admin urls
    path("admin/", admin.site.urls),
    # ...
    # /, /login, /register, /forgot-password
    path("", include("accounts.urls")),
    # ...
    # dashboard/,
    path("", include("analytics.urls")),
    # ...
    # notification/send, notifications
    path("", include("core.urls")),
    # ...
    # website/add/, website/delete/<id>/, website/<id>/
    path("", include("websites.urls")),
    # ...
    # all the api urls
    path("api/", include(router.urls)),
    # ...
    # service worker file
    re_path(
        r"^firebase-messaging-sw.js",
        TemplateView.as_view(
            template_name="firebase-messaging-sw.js",
            content_type="application/javascript",
        ),
    ),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(
        [
            path("__debug__/", include(debug_toolbar.urls)),
        ]
    )


def error_page(request, *args, **kwargs):
    return render(request, "404.html")


handler404 = error_page
handler500 = error_page
handler403 = error_page
handler400 = error_page

pushify/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render

from pushify.routers import router


urlpatterns = [
    # admin urls
    path("admin/", admin.site.urls),
    # ...
    # /, /login, /register, /forgot-password
    path("", include("accounts.urls")),
    # ...
    # dashboard/,
    path("", include("analytics.urls")),
    # ...
    # notification/send, notifications
    path("", include("core.urls")),
    # ...
    # website/add/, website/delete/<id>/, website/<id>/
    path("", include("websites.urls")),
    # ...
    # all the api urls
    path("api/", include(router.urls)),
    # ...
    # service worker file
    re_path(
        r"^firebase-messaging-sw.js",
        TemplateView.as_view(
            template_name="firebase-messaging-sw.js",
            content_type="application/javascript",
        ),
    ),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(
        [
            path("__debug__/", include(debug_toolbar.urls)),
        ]
    )


def error_page(request, *args, **kwargs):
    return render(request, "404.html")


handler404 = error_page
handler500 = error_page
handler403 = error_page
handler400 = error_page

websites/urls.py
from django.urls import path

from websites.views import (
    WebsiteAddView,
    WebsiteEditView,
    WebsitesListView,
    WebsiteDeleteView,
)

app_name = "websites"

urlpatterns = [
    path("websites/", WebsitesListView.as_view(), name="websites_list_view"),
    path("website/add/", WebsiteAddView.as_view(), name="website_add_view"),
    path("website/<slug:slug>/", WebsiteEditView.as_view(), name="website_edit_view"),
    path(
        "website/delete/<int:pk>/",
        WebsiteDeleteView.as_view(),
        name="website_delete_view",
    ),
]

templates/includes/modals/logout_modal.html
<!-- Logout Modal-->
<div
  class="modal fade"
  id="logoutModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header pt-3 pb-0">
        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
      <div class="modal-footer py-2">
        <button class="btn btn-sm btn-secondary shadow-sm" type="button" data-dismiss="modal">Cancel</button>
        <form action="{% url 'accounts:logout_view' %}" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn btn-sm btn-danger shadow-sm">
            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-1"></i>
            Logout
          </button>
        </form>
      </div>
    </div>
  </div>
</div>

templates/includes/modals/website_delete_modal.html
<!-- Logout Modal-->
<div
  class="modal fade"
  id="websiteDeleteModal{{ website_obj.pk }}"
  tabindex="-1"
  role="dialog"
  aria-labelledby="websiteDeleteModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header pt-3 pb-0">
        <h5 class="modal-title" id="websiteDeleteModalLabel">Are you sure ? </h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        Select delete button to delete the website with domain "{{ website_obj.domain }}".
        <p><strong>Note: </strong> All the notifications associated with this website will be deleted.</p>
    </div>
      <div class="modal-footer py-2">
        <button class="btn btn-sm btn-secondary shadow-sm" type="button" data-dismiss="modal">Cancel</button>
        <form action="{% url 'websites:website_delete_view' website_obj.pk %}" method="POST">
            {% csrf_token %}
          <button type="submit" class="btn btn-sm btn-danger shadow-sm">
            <i class="fas fa-trash fa-sm fa-fw mr-2"></i>
            Delete
          </button>
        </form>
      </div>
    </div>
  </div>
</div>